-- =============================================================================
-- [GENIE ONE EXTENSION — ADDITIVE ONLY] ext_delivery_order
-- -----------------------------------------------------------------------------
-- Delivery-reliability fact: one row per (synthetic) delivery order, with promised
-- vs actual dates, gallons, and verified runout / late flags. Feeds mv_delivery and
-- account_retention_base (the "verified service failure" half of the churn-bomb aha).
--
-- SOURCE: ext_delivery_order_seed — a SYNTHETIC table generated by
-- src/setup_ext/gen_ext_data.py (Spark+Faker, story-driven, keyed to existing
-- opportunity_ids). Seed it via the setup task BEFORE running this pipeline, the
-- same way dim_salesforce_opportunity is seeded for the existing pipeline.
--
-- ADDITIVE: reads a NEW synthetic seed table; writes a NEW table. Touches nothing
-- existing. A "reported" runout only becomes runout_verified_flag=1 when the seed
-- carries an operational delivery record (never inferred from complaints).
-- =============================================================================
CREATE OR REFRESH MATERIALIZED VIEW ext_delivery_order (
  CONSTRAINT valid_opportunity EXPECT (opportunity_id IS NOT NULL),
  CONSTRAINT nonneg_gallons    EXPECT (gallons >= 0)
)
COMMENT 'Additive Genie One extension: synthetic per-order delivery reliability (runout/late), keyed to existing opportunities. is_synthetic = true.'
AS
SELECT
  s.delivery_id,
  s.opportunity_id,
  CAST(s.delivery_date  AS DATE)      AS delivery_date,
  CAST(s.promised_date  AS DATE)      AS promised_date,
  CAST(s.gallons        AS DOUBLE)    AS gallons,
  CAST(s.runout_verified_flag AS INT) AS runout_verified_flag,
  -- late = actual after promised (guard nulls); also honor an explicit seed flag
  CASE WHEN COALESCE(s.late_delivery_flag, 0) = 1
         OR (s.delivery_date IS NOT NULL AND s.promised_date IS NOT NULL
             AND s.delivery_date > s.promised_date)
       THEN 1 ELSE 0 END              AS late_delivery_flag,
  CAST(s.order_status   AS STRING)    AS order_status,
  TRUE AS is_synthetic
FROM ext_delivery_order_seed s;
